# Generated by Django 4.0.6 on 2022-08-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_img')),
                ('Discount_Deal', models.CharField(max_length=255)),
                ('Quote', models.CharField(max_length=255)),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
