# Generated by Django 4.0.6 on 2022-08-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_information',
            new_name='Additional_informations',
        ),
    ]
