# Generated by Django 4.0.6 on 2022-08-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_additional_information_additional_informations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_informations',
            new_name='Additional_Information',
        ),
    ]
