# Generated by Django 4.0.6 on 2022-08-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
